Basic imports and environment checks:
- PyTorch version verification is essential for reproducibility
- CUDA availability check - we'll need GPU access for future assignments
- If CUDA isn't available, try nvidia-smi in terminal to check GPU status

In [2]:
import torch

print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")

PyTorch version: 2.6.0
CUDA available: False


Converting Python list to tensor - torch.as_tensor() is preferred over torch.tensor()
as it can share memory with original data

In [3]:
x = [1, 2, 3, 4, 5]
x = torch.as_tensor(x)
print(x)

tensor([1, 2, 3, 4, 5])


Creating zero-filled tensor - useful for initializing buffers or placeholder tensors

In [4]:
x = torch.zeros(3, 4)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


Creating tensor filled with ones - commonly used for masks or initialization

In [5]:
x = torch.ones(3, 4)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


Creating tensor with custom fill value - useful when you need specific constant values

In [6]:
x = torch.full((3, 4), fill_value=2)
print(x)

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]])


Random tensor from normal distribution - key for weight initialization

In [7]:
x = torch.randn(3, 4)
print(x)

tensor([[-0.5973,  0.0940,  0.0424,  1.7002],
        [-0.1334,  1.2279, -0.0946, -0.3441],
        [-0.8992, -0.7610,  0.1679,  0.1762]])


`zeros_like` creates tensor with same shape/dtype as input but filled with zeros

In [8]:
x = torch.randn(3, 4)
y = torch.zeros_like(x)
print(y)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


`ones_like` - similar to before but fills with ones

In [9]:
x = torch.randn(3, 4)
y = torch.ones_like(x)
print(y)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


`full_like` - creates tensor matching input shape but with custom fill value

In [10]:
x = torch.randn(3, 4)
y = torch.full_like(x, 5)
print(y)

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])


`new_tensor` creates tensor with inherited properties (device/dtype) from source

In [11]:
x = torch.zeros(3, 4, dtype=torch.bool)
y = x.new_tensor([1])
print(x)
print(y)
print(x)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
tensor([True])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


Broadcasting example with 2D tensors - shows automatic size matching

In [12]:
x = torch.ones(5, 1)
y = torch.ones(1, 5)
z = x + y
print(x)
print(y)
print(z, z.shape)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]])
tensor([[1., 1., 1., 1., 1.]])
tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]) torch.Size([5, 5])


Complex broadcasting with 5D tensors - demonstrates multi-dimension expansion

In [13]:
x = torch.ones(1, 1, 1, 1, 1)
y = torch.ones(2, 1, 3, 1, 2)
z = x + y
print(z, z.shape)

tensor([[[[[2., 2.]],

          [[2., 2.]],

          [[2., 2.]]]],



        [[[[2., 2.]],

          [[2., 2.]],

          [[2., 2.]]]]]) torch.Size([2, 1, 3, 1, 2])


Mean reduction - shows global and dimensional mean calculations

In [14]:
x = torch.ones(3, 4, 5)
print(x.mean())
print(x.mean(-1))

tensor(1.)
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


Sum reduction - demonstrates summing across specified dimensions

In [15]:
x = torch.ones(3, 4, 5)
print(x.sum(dim=0))
print(x.sum(dim=(1, 2)))

tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]])
tensor([20., 20., 20.])


`keepdim`` usage - shows difference in output shapes

In [16]:
x = torch.ones(3, 4, 5)
y = x.sum(dim=(1, 2))
z = x.sum(dim=(1, 2), keepdim=True)
print(y, y.shape)
print(z, z.shape)

tensor([20., 20., 20.]) torch.Size([3])
tensor([[[20.]],

        [[20.]],

        [[20.]]]) torch.Size([3, 1, 1])


Type conversion example - converting float tensor to long (int64)

In [17]:
x = torch.randn(5, 5)
print(x.to(torch.long))

tensor([[ 0,  0,  0,  0,  0],
        [ 0,  1,  0,  0,  0],
        [ 1,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0, -1,  0,  0,  2]])


Reshaping with view - maintains underlying data pointer

In [18]:
x = torch.randn(2, 3, 2)
y = x.view(6, 2)
z = x.view(-1, 2)
print(y, y.shape)
print(z, z.shape)

tensor([[-1.3345, -0.5327],
        [-1.3318, -0.1619],
        [ 0.5496,  1.1547],
        [ 0.1888,  0.5211],
        [-0.0891,  0.4828],
        [-0.9473, -0.6930]]) torch.Size([6, 2])
tensor([[-1.3345, -0.5327],
        [-1.3318, -0.1619],
        [ 0.5496,  1.1547],
        [ 0.1888,  0.5211],
        [-0.0891,  0.4828],
        [-0.9473, -0.6930]]) torch.Size([6, 2])


Permute operation - reorders dimensions of tensor

In [19]:
x = torch.randn(2, 3, 2)
y = x.permute(1, 2, 0)
print(y, y.shape)

tensor([[[ 0.4092,  0.7303],
         [-1.4161, -0.0332]],

        [[ 1.0715,  0.8298],
         [ 1.1001, -0.3272]],

        [[ 0.7307, -0.6910],
         [ 0.5101,  0.3695]]]) torch.Size([3, 2, 2])


Concatenation along specified dimension

In [20]:
x = torch.ones(2, 3)
y = torch.ones(2, 3)
z = torch.cat([x, y], dim=0)
print(z, z.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) torch.Size([4, 3])


Stack operation - adds new dimension for combining tensors

In [21]:
x = torch.ones(2, 3)
y = torch.ones(2, 3)
z = torch.stack([x, y], dim=1)
print(z, z.shape)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]) torch.Size([2, 2, 3])


Performance comparison: Python list operations vs PyTorch operations

In [22]:
import time


def add_two_lists(x, y):
    z = []
    for i, j in zip(x, y):
        z.append(i + j)
    return z


x = torch.ones(5000)
y = torch.ones(5000)
t1 = time.time()
z = add_two_lists(x, y)
print(f"{time.time() - t1:.4f} sec.")

0.0109 sec.


PyTorch vectorized operation - significantly faster

In [23]:
def add_two_lists(x, y):
    return x + y


x = torch.ones(5000)
y = torch.ones(5000)
t1 = time.time()
z = add_two_lists(x, y)
print(f"{time.time() - t1:.4f} sec.")

0.0015 sec.


Type conversion examples - showing different conversion methods

In [24]:
x = torch.randn(3, 3)
y = torch.zeros(5, 2, dtype=torch.long)
print(x.to(torch.float32))
print(x.to(torch.bool))
print(x.to(y))

tensor([[-0.3746,  0.1918, -2.2743],
        [-0.5862, -2.0558, -0.0281],
        [-0.6524, -0.4068, -0.1138]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
tensor([[ 0,  0, -2],
        [ 0, -2,  0],
        [ 0,  0,  0]])


`arange` examples - different ways to create sequences

In [25]:
x = torch.arange(8)
print(x)
y = torch.arange(2, 8)
print(y)
z = torch.arange(3, 10, step=2)
print(z)

tensor([0, 1, 2, 3, 4, 5, 6, 7])
tensor([2, 3, 4, 5, 6, 7])
tensor([3, 5, 7, 9])


In [26]:
x = torch.tensor([1, 2, 3,4,5,6,7,8])
print(x[:3])

tensor([1, 2, 3])


In [31]:
# Create a 2D tensor
x = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Transpose the tensor
x_transposed = x.mT

print(x_transposed)

tensor([[1, 4],
        [2, 5],
        [3, 6]])
